name: birdseye
description: FRC Scouting App
publish_to: 'none'
version: 2.1.1

environment:
  sdk: '^3.8.1'

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_svg: any
  flutter_swipe_action_cell: ^3.1.2
  go_router: ^16.0.0
  http: any
  localstore: ^1.3.5
  markdown_widget: any
  shared_preferences: ^2.1.2
  stock: ^1.0.1
  supabase_flutter: ^2.3.1
  url_launcher: any

dev_dependencies:
  flutter_lints: any
  build_runner: any
  build_verify: any
  go_router_builder: any

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/documents/
  fonts:
    - family: HemiHead
      fonts:
        - asset: assets/fonts/hemi-head.otf
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: Verdana
      fonts:
        - asset: assets/fonts/verdana.ttf
        - asset: assets/fonts/verdanai.ttf
          style: italic
        - asset: assets/fonts/verdanab.ttf
          weight: 700
        - asset: assets/fonts/verdanaz.ttf
          style: italic
          weight: 700